# The bot token which you obtained from the Discord developer site. Never share this.
# bot-token:

# The channel IDs in which the rules and motions, respectively, are posted.
# rules-channel:
# motions-channel:

# The frequency with which rdan should check for finished votes, in seconds.
# Usually about 10-15 seconds is fine.
# The default if unspecified is 15 seconds.
# rdan will immediately end a vote if all players vote, as long as the vote may end when all players vote.
# vote-poll-frequency:

# Whether players who haven't voted on a vote should be reminded to vote before it ends.
# vote-reminders: false
# How far in advance, in minutes, players should be warned about impending votes which they haven't yet voted on.
# vote-reminder-interval: 10

# The reactions which the bot should use to react to vote messages, by default.
# The reactions will be used in order.
# The default is an empty list of reactions.
# default-voting-reactions: []

# The players who will be playing the game.
# For each player, a human-readable name, and their Discord user ID should be provided.
# players:
#   - name:
#     id:
#   - name:
#     id:
